name: Build and Deploy to Cloud Run

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "latest"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Create main .env file
        run: |
          touch .env
          echo "AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }}" >> .env
          echo "JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }}" >> .env
          echo "JWT_REFRESH_AGE_S=${{ secrets.JWT_REFRESH_AGE_S }}" >> .env
          echo "NEXT_PUBLIC_GRAPHQL_URL=${{ secrets.NEXT_PUBLIC_GRAPHQL_URL }}" >> .env
          cat .env

      - name: Create Prisma .env file
        run: |
          touch prisma/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> prisma/.env
          cat prisma/.env

      - name: Docker Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/cms:latest .

      - name: Docker Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cms:latest

      - name: Deploy
        run: |
          gcloud run deploy cms \
          --port 80 \
          --region asia-east1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cms:latest \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Run Database Migrations
        run: npm run db:up
